# deploy-neon.yml

name: Run Alembic Migrations on Neon

on:
  workflow_call:
    secrets:
      NEON_DB_SYNC:
        required: true # Aseguramos que el caller lo pase

jobs:
  migrate:
    name: Run Alembic migrations on Neon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install production dependencies (for migrations)
        run: pip install -r requirements-prod.txt

      - name: Run migrations
        run: make alembic-upgrade
        env:
          ENVIRONMENT: production
          PROJECT_NAME: BackendBase
          DB_URL_SYNC: ${{ secrets.NEON_DB_SYNC }}